### ISSUE TITLE
segment fault  under centos7 

### ISSUE THREAD

**Issue by keainala** [igd-geo/schwarzwald#2]
when use Schwarzwald --tiler -i /path/to/your/LAS/files -o /output/path/for/3D/tiles --output-format 3DTILES  ，it run error

**Comment by michel-kraemer** [comment]
Can you give us a little more information please? For example, what data set are you trying to convert? What error message do you get exactly?

**Comment by keainala** [comment]
I want to convert las to 3dtiles   
Input files:
"i/zt-Cloud.las"
 [00:00:00] indexing: 0 / 92.775M loading: 0 / 92.775M   
this is  error

**Comment by michel-kraemer** [comment]
Is your input file OK? Did you check it with `lasvalidate`?
https://rapidlasso.com/lasvalidate/

**Comment by keainala** [comment]
I didn't，but I use las2las in https://github.com/LAStools/LAStools   it work well
